### ISSUE TITLE
Why have different visibility vector in a same pose cluster

### ISSUE THREAD

**Issue by minorli96** [vobecant/DummyNet#2]
Dear @vobecant 
        When i try to run the pose generate.py, I load the joints_pca_etc.npz file  as  base to generate new pose. And found some confusion in hoints_pca_etc.npz file,  for example,  I think joints_pca['clusters'][00000] is a pose cluster , but why have different active_joints in this pose cluster?  Don't active points and visibility vector mean the same thing? Thanks for your reply, your reply helped me a lot, thx!

**Comment by vobecant** [comment]
@dhurych, can you please have a look at this? Thanks!

**Comment by minorli96** [comment]
@vobecant
Thank for your reply bro!
Beside this , I want to ask you How closely related is Keypoint、mask and Appearance vector? in other words,  I extract appearance vector from a common pose person image, it can be fill to a uncommon pose mask use DummyGAN?   
In  my experiment,  when I try to use sample['app_vec'](privode by you) to fill a novel pose mask , finaly yeild a bad result. I guess maybe cause by mask(generate by myself)  and appearance vector(sample).

**Comment by vobecant** [comment]
Dear @lulubbb, thank you very much for your interest in our paper.
To answer your previous question: I think that there might be more than a single visibility vector in one pose cluster. Are those different visibility vectors considerably different?
And about your current question: I guess that if you use some really uncommon poses, our method can yield non-perfect results.

**Comment by minorli96** [comment]
Dear @vobecant 
This work is perfect！
Abount first question, I carefully  check the cluster keypoints sample and read the appendix of DummyNet paper.
In your paper said: 'we form clusters with similar visibility of skeleton keypoints'  , according to this I understand as : a cluster only have one visibility vector, and all pose from one cluster have same number of keypoints.
About Mask and Keypoint: give an extreme example, appearance vector extract from a site pose person ,  it can be used to fill a mask generated by a jump man?  Does the filling process require key points as prior knowledge. 

Good afternoon in Czech time！

**Comment by vobecant** [comment]
Dear @lulubbb,
1) as you have just cited, the clusters contain _similar_ visibility vectors, which means that they do not need to be exactly the same. Imagine that you have two almost-equal poses where one has one of the joints labeled as visible whereas the other one has it occluded. Then, it might happen that these two end up in the same cluster.
2) Using similar poses for appearance and for generation can improve the results.

**Comment by minorli96** [comment]
Dear @vobecant  @dhurych ,
        Thank you all,  I will try to understand the problem mentioned above.
        Wish you guys good luch. 👍
